### ISSUE TITLE
Suggestion: how about using Google's Maven mirror in maven-example/pom.xml?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-build-samples#9]
How about using Google's Maven mirror (https://storage-download.googleapis.com/maven-central/index.html) in [maven-example/pom.xml](https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/maven-example/pom.xml)? The proximity from Google Cloud Build to the mirror within GCP should be good for cloud build users for the following reasons:

- It's fast.
- It reduces unnecessary traffic that crosses the boundary of Google Cloud.

**Comment by glasnt** [comment]
According to the link provided, "This is not an officially supported Google product."

With the release of Assured OSS, there's documentation there for how to use alternative mirrors https://cloud.google.com/assured-open-source-software/docs/download-java-packages
