### ISSUE TITLE
Update cloudbuild.yaml for java 11 (or 17)

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/cloud-build-samples#97]

**Comment by fmichaelobrien** [comment]
I will work on this and post back the fork PR

**Comment by rogerthatdev** [comment]
Hi @fmichaelobrien!

Do you have any updates to provide for this issue?

**Comment by fmichaelobrien** [comment]
Roger, not yet, in my queue, sorry for the delay, I will revisit this weekend.  Java based sdk deployment of GCP landing zones as an alternative for java devs (without terraform or kubectl knowledge) is a priority on the lz sides

**Comment by glasnt** [comment]
A number of java samples were updated to Springboot 3 and Java 17 in #136. I believe all Java samples are currently 17
